# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f09fad4681e9c76efc7c4997e12876f46e76b1ac1e65c3bc3f5998d2668fdcc7b427b485f1aeaf68d8d6668bb57f080e486c9392dc9136f7e940e1702186b89d

test:
  secret_key_base: 153109086cd882ae534672f0c51b89ab5f6eee5cce0a96ebf4dd4b9f56465f4b2c8dc83a70bbe8e88338f94318536a12e1bcc9e6182146768c157b7f8a2cd3f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
